### ISSUE TITLE
Scatter Chart

### ISSUE THREAD

**Issue by orangelabs-dev** [coroo/nova-chartjs#22]
As Chart JS Integration’s user,
I need to have Scatter chart
So that I can combine an Area + Scatter chart

**Comment by coroo** [comment]
Hi @orangelabs-dev , thank you for your feedback for this package. For scatter-chart, I already build it using [chart-js-scatter](https://www.chartjs.org/docs/latest/charts/scatter.html) and update documentation in https://coroo.github.io/nova-chartjs/#/?id=scatter-chart.
Unfortunately, that scatter only available in custom data only for now. Hopefully this still capture your need.

For using model, I still figuring out for the test case using real data since I never use that scatter (use x and y) in my dashboard. If you have any test case for real data (in database), please let me know :)
