### ISSUE TITLE
Set default backgroundColor and borderColor for custom chart

### ISSUE THREAD

**Issue by phuclh** [coroo/nova-chartjs#36]
Normally, when I use the custom chart I need to build a data array. Something like this:

```
$chartData = [];
        foreach ($report['chartData'] as $key => $item)
        {
            $chartData[] = [
                'barPercentage' => 0.5,
                'label'         => $key,
                'borderColor'   => sprintf('#%06X', mt_rand(0, 0xFFFFFF)),
                'data'          => array_values($item),
            ];
        };
```
You can see I have to set an extra element with the key `borderColor` manually to set the color for line chart, otherwise it won't have the color. Would you consider to set the default color for the custom chart.

Thank you!

**Comment by coroo** [comment]
Hi @phuclh ,

Base on chartjs.org, there will be only one default color : `'rgba(0, 0, 0, 0.1)'`
https://www.chartjs.org/docs/latest/charts/bar.html

For using API / Laravel Model, we hit the API first, then populate array include of default border colors.

Different for custom chart, the tricky one is about the data. so basically we don't count your data first, then instead sent it directly to create chart. The impact is more about performance for custom data and complication in nova-chartjs code, if we do loop in your data and add your default border color.

To add your custom border, actually you can use: 
```
        $chartData = [];
        $borderColors = array('#bc644b', '#592b74', '#63c4f9', '#3cccb6', '#07d5f4', '#e85c2f', '#820fd5');
        foreach ($report['chartData'] as $key => $item)
        {
            $chartData[] = [
                'barPercentage' => 0.5,
                'label'         => $key,
                'borderColor'   => $borderColors[$key],
                'data'          => array_values($item),
            ];
        };
```

I think this is the best practice for now, since its only add 2 line of codes rather change the behaviour of custom chart in nova-chartjs.  🙏
