### ISSUE TITLE
Problems getting charts to display.

### ISSUE THREAD

**Issue by tgrantmartin** [coroo/nova-chartjs#41]
I'm using Nova 2.12 and nova-chartjs v 0.2.4. I'm getting js errors.
<img width="651" alt="image" src="https://user-images.githubusercontent.com/5315580/79793462-3af6e680-8316-11ea-99d8-89430623b9ec.png">
used composer to install, and pasted the code for the chart from the example into the return of the cards method of the NovaServiceProvider Class.

**Comment by coroo** [comment]
Hi @tgrantmartin , i already try to re-use this v0.2.4 in my project and doesn't seems any error related. Can you try to relaunch your website in incognito? I need to make sure this not regarding cookies related.

**Comment by MrHesus** [comment]
Iam having the same problem over here.

On my dashboard it displays this:
![image](https://user-images.githubusercontent.com/25330441/80585729-1edcfe80-8a14-11ea-8940-b9da00f99d86.png)

Console:
![image](https://user-images.githubusercontent.com/25330441/80585771-2ef4de00-8a14-11ea-884e-37fd4c6ef739.png)

Console in incognito:
![image](https://user-images.githubusercontent.com/25330441/80585870-55b31480-8a14-11ea-8a0e-d25f9ecb5d96.png)

Code:
![image](https://user-images.githubusercontent.com/25330441/80585919-682d4e00-8a14-11ea-8c93-2a7ba641058e.png)

**Comment by coroo** [comment]
Hi @tgrantmartin and @MrHesus , 

Sorry since I can't reproduce your error in my side. But after help from @lenssoft in this [PR-47](https://github.com/coroo/nova-chartjs/pull/47) , he help me a lot to reproduce the same error with your case. So, if you dont mind, can you also check from your side to test this beta version in :
```
composer require coroowicaksono/chart-js-integration:dev-issues-41
```

If you still found any error, please dont hestiate to share in here. 

Thank you.

**Comment by tgrantmartin** [comment]
At first glance, this appears to work perfectly.

**Comment by coroo** [comment]
Release in [v0.2.5](https://github.com/coroo/nova-chartjs/tree/v0.2.5)
