### ISSUE TITLE
Unable to set fill for linechart

### ISSUE THREAD

**Issue by michaelw85** [coroo/nova-chartjs#45]
Fill is always set to false in code [here](https://github.com/coroo/nova-chartjs/blob/master/src/LineChart.php#L36)

I can understand that you would like to default this to false but I would not forcefully overwrite when a developer sets the option to true.

**Comment by coroo** [comment]
Hi @michaelw85 , I just check again the line chart and area chart documentation. And i think before that we added default value for line-chart since the only differences between line and area is about fill area under the line. I know its about forcefully method, but is there any scenario that develop / user will set fill option to true, instead of using area-chart directly?

**Comment by michaelw85** [comment]
@coroo I wanted to use line with fill because the area chart did not support the RGBA value for background color. Eventually I was forces to use a bar chart as base class so I could use the fill + RGBA values. But the bar chart X-axis alignment is different from line/area charts.

**Comment by coroo** [comment]
Hi @michaelw85 , for RGBA value, I still doing development and testing in [issues-46 repo](https://github.com/coroo/nova-chartjs/tree/issues-46). Hopefully we can use area with RGBA chart soon, sorry for the inconvenience :)

**Comment by coroo** [comment]
Solve by ticket #46
