### ISSUE TITLE
How do I display labels on data for any type of chart?

### ISSUE THREAD

**Issue by oleksandr-roskovynskyi** [coroo/nova-chartjs#48]
How to do it with your package? (screenshot of the library plugin https://github.com/chartjs/chartjs-plugin-datalabels )

![image](https://user-images.githubusercontent.com/57599426/83636771-2f523d00-a5af-11ea-836e-16aef393746a.png)

**Comment by coroo** [comment]
Hi @oleksandr-roskovynskyi , thank you for your interest in this package. 
Unfortunately, we not yet used any additional plugin from chart-js like [datalabels](https://github.com/chartjs/chartjs-plugin-datalabels). 

We label this issue as `enhancement` so that we can have this feature in future and will update this ticket again soon.

**Comment by coroo** [comment]
Hi @oleksandr-roskovynskyi , we already add datalabels plugin to our package. But it still in branch issues-48 since we still try to do some testing. Also, if you dont mind. It will be great if you can help us to do testing for using datalabels at this version:

```
composer require coroowicaksono/chart-js-integration:dev-issues-48
```

For detail documentation, please take a look in this [plugin documentation](https://coroo.github.io/nova-chartjs/#/plugin?id=nova-chartjs-plugin).

**Comment by coroo** [comment]
Hi @oleksandr-roskovynskyi , we already add datalabels plugin to our package. But it still in branch [issues-48](https://github.com/coroo/nova-chartjs/tree/issues-48) since we still try to do some testing. Also, if you dont mind. It will be great if you can help us to do testing for using datalabels at this version:

```
composer require coroowicaksono/chart-js-integration:dev-issues-48
```

For detail documentation, please take a look in this [plugin documentation](https://coroo.github.io/nova-chartjs/#/plugin?id=nova-chartjs-plugin).
