### ISSUE TITLE
How to cancel the cache?

### ISSUE THREAD

**Issue by haxifang-aircos** [coroo/nova-chartjs#58]
Hi, I found that the statistics are not up to date every time, and the page needs to be refreshed. Is this the reason for caching?

**Comment by haxifang-aircos** [comment]
To add a question, for example, if I open the A tab, and then open the B tab, it will appear that the B tab displays the data of the A tab. If I refresh the page on the B tab, the data will be the normal B tab. data.

**Comment by coroo** [comment]
Hi @haxifang-aircos , sorry for late response.
For your case, do you use custom dashboard by laravel nova at here https://nova.laravel.com/docs/2.0/customization/dashboards.html#overview ?

If yes, I already try that case, and I think its an error in Laravel Nova because when I create default trend (https://nova.laravel.com/docs/2.0/metrics/defining-metrics.html#trend-metrics), the chart on trend won't change just like our chart-js. Can you also try that? Since I need your help to make sure if my statement is correct.

For workaround, you can use a simple dashboard (without tab) or using this button: https://coroo.github.io/nova-chartjs/#/?id=add-refresh-button

Hope this answer fine with you
